### PR TITLE
docker-compose with postgres

### PR DESCRIPTION
**Pull request by markusbnet**
- [x] Update docker-compose with postgres data store.
- [x] app config should be loaded through .env
- [x] Create tables on startup
- [x] Defined models and schemas
- [x] Follow tutorial - https://fastapi.tiangolo.com/tutorial/sql-databases/
- [x] Store data generated from the scheduler for storage accounts.

### CODE REVIEW

**Comment by markusbnet** [comment]
@HarleyB123 very drafty but moving towards datastore.

**Comment by HarleyB123** [comment]
Yooo is this suppose to work?

tried it with .env and docker-compose and got some errors on both Postgres and the Webapp - will send errors tomorrow

**Comment by markusbnet** [comment]
amazingly i have broken it haha not working for me either

**Comment by markusbnet** [comment]
Screen Shot 2021-01-12 at 21 02 30

Now reads from database. Data still needs to be manually added.

**Comment by markusbnet** [comment]
@HarleyB123 your latest commit 'works on my machine'. Looks good. fast as well

**Pull request merged**
