### PR TITLE
gets sub and resource group from id

### PR DESCRIPTION
**Pull request by HarleyB123**

### CODE REVIEW

**Comment by HarleyB123** [comment]
black hasn't formatted this well, happy to move to flake8 or stick with it

**Comment by HarleyB123** [comment]
@markusbnet will have to do ```docker-compose up --build``` when you want to try this due to new req

**Comment by HarleyB123** [comment]
Buttons don't do anything yet, but is a start

**Review by markusbnet — APPROVED** [review]
lavely

**Pull request merged**
